Varshini Narayanan

This code scrapes data on the largest publically traded companies by market cap. Foreign Domiciled and repeat corporations are manually removed.

51 lines of code

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# request page
url = "https://finance.yahoo.com/research-hub/screener/largest_market_cap/"

request_headers = {
    "User-Agent": "For the purpose of a class project varshi@uchicago.edu "
}

response = requests.get(url, headers=request_headers)
soup = BeautifulSoup(response.text, "html.parser")

# find table
table = soup.find("table")

# find the correct headers
column_headers = [
    th.text.strip()
    for th in table.find("thead").find_all("th")
]

# align to headers
rows = table.find("tbody").find_all("tr")

data = []
for row in rows:
    cells = [td.text.strip() for td in row.find_all("td")]
    data.append(dict(zip(column_headers, cells)))

# made dataframe
df = pd.DataFrame(data)

# Clean ticker symbols
df["Symbol"] = df["Symbol"].str.split().str[-1]


df

,,Symbol,Name,1D Chart,Price (Intraday),Change,Change %,Volume,Avg Vol (3M),Market Cap,P/E Ratio (TTM),52 Week Range,Region,Follow
0,1,AZULD,Azul S.A.,,"1,066.67",0.00,0.00%,1,19,"1,451.912T",--,"670.00 39,750.00",US,
1,2,NVDA,NVIDIA Corporation,,172.05,-2.14,-1.23%,177.723M,181.589M,4.189T,44.64,86.62 212.19,US,
2,3,AAPL,Apple Inc.,,275.91,-0.58,-0.21%,49.149M,47.944M,4.055T,34.18,169.21 288.62,US,
3,4,GOOGL,Alphabet Inc.,,331.54,-1.50,-0.45%,79.776M,36.103M,4.016T,33.52,140.53 349.00,US,
4,5,GOOG,Alphabet Inc.,,331.33,-2.01,-0.60%,47.323M,23.254M,4T,33.52,142.66 350.15,US,
5,6,MSFT,Microsoft Corporation,,393.74,-20.45,-4.94%,55.083M,28.583M,2.926T,25.73,344.79 555.45,US,
6,7,AMZN,"Amazon.com, Inc.",,222.90,-10.09,-4.33%,68.885M,40.68M,2.383T,33.72,161.38 258.60,US,
7,8,TSM,Taiwan Semiconductor Manufacturing Company Lim...,,330.73,+4.99,+1.53%,13.769M,12.674M,1.715T,27.17,134.25 351.33,US,
8,9,META,"Meta Platforms, Inc.",,670.33,+1.34,+0.20%,14.172M,17.617M,1.696T,29.45,479.80 796.25,US,
9,10,TSLA,"Tesla, Inc.",,397.36,-8.65,-2.13%,65.297M,72.701M,1.491T,390.70,214.25 498.83,US,
10,11,AVGO,Broadcom Inc.,,310.51,+2.46,+0.80%,37.996M,30.735M,1.472T,67.16,138.10 414.61,US,
11,12,BRK-A,Berkshire Hathaway Inc.,,"756,943.00",-947.00,-0.12%,248,785,1.089T,15.78,"685,150.00 812,855.00",US,
12,13,BRK-B,Berkshire Hathaway Inc.,,503.89,+0.06,+0.01%,4.091M,4.982M,1.087T,15.78,455.19 542.07,US,
13,14,JPM,JPMorgan Chase & Co.,,310.16,-7.11,-2.24%,7.155M,10.146M,1.042T,15.73,202.16 337.25,US,
14,15,WMT,Walmart Inc.,,126.94,-1.06,-0.83%,30.436M,29.642M,1.012T,38.96,79.81 129.41,US,
15,16,LLY,Eli Lilly and Company,,"1,020.84",-86.28,-7.79%,6.181M,3.373M,915.139B,43.72,"623.78 1,133.95",US,
16,17,TCTZF,Tencent Holdings Limited,,70.45,-2.59,-3.55%,"2,700","24,025",635.543B,22.09,53.20 89.10,US,
17,18,V,Visa Inc.,,329.13,-0.82,-0.25%,6.693M,7.188M,634.576B,30.90,299.00 375.51,US,
18,19,TCEHY,Tencent Holdings Limited,,69.66,-1.02,-1.44%,1.146M,2.455M,628.416B,22.09,52.30 87.68,US,
19,20,SSNLF,"Samsung Electronics Co., Ltd.",,65.21,0.00,0.00%,200,25,620.176B,25.36,40.60 65.21,US,
20,21,XOM,Exxon Mobil Corporation,,146.08,-1.51,-1.02%,15.277M,17.789M,616.044B,21.45,97.80 147.84,US,
21,22,JNJ,Johnson & Johnson,,237.79,+3.32,+1.42%,8.362M,9.027M,572.906B,21.13,141.50 235.83,US,
22,23,BAC,Bank of America Corporation,,54.94,-0.44,-0.79%,27.362M,37.436M,548.754B,14.29,33.07 57.55,US,
23,24,ASML,ASML Holding N.V.,,"1,350.16",+11.03,+0.82%,1.672M,1.705M,524.061B,48.17,"578.51 1,493.48",US,
24,25,ASMLF,ASML Holding N.V.,,"1,343.46",+13.26,+1.00%,133,"1,433",521.461B,48.17,"585.54 1,495.03",US,

In [34]:
#remove foreign domicilced companies

df["Change"].dtype
df = df[df["Change"] != 0.0]

#remove tencent seperately
df = df[~df["Symbol"].isin(["TCTZF", "TCEHY"])]

In [ ]:
#convert market cap values from str (13T) into numerical value

def parse_market_cap(x):
    if pd.isna(x):
        return None
    x = x.replace(",", "")
    if x.endswith("T"):
        return float(x[:-1]) * 1e12
    if x.endswith("B"):
        return float(x[:-1]) * 1e9
    if x.endswith("M"):
        return float(x[:-1]) * 1e6
    return float(x)

df["Market Cap Num"] = df["Market Cap"].apply(parse_market_cap)

/var/folders/vy/c51m8q751_72tx9f0b1r4blc0000gn/T/ipykernel_49721/3386891294.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Market Cap Num"] = df["Market Cap"].apply(parse_market_cap)

In [35]:
#keep only largest marketcap listing for companies that appear multiple times
df = (
    df.sort_values("Market Cap Num", ascending=False)
      .drop_duplicates(subset="Name", keep="first")
      .reset_index(drop=True)
)

df

,,Symbol,Name,1D Chart,Price (Intraday),Change,Change %,Volume,Avg Vol (3M),Market Cap,P/E Ratio (TTM),52 Week Range,Region,Follow,Market Cap Num
0,2,NVDA,NVIDIA Corporation,,172.05,-2.14,-1.23%,177.723M,181.589M,4.189T,44.64,86.62 212.19,US,,4.189000e+12
1,3,AAPL,Apple Inc.,,275.91,-0.58,-0.21%,49.149M,47.944M,4.055T,34.18,169.21 288.62,US,,4.055000e+12
2,4,GOOGL,Alphabet Inc.,,331.54,-1.50,-0.45%,79.776M,36.103M,4.016T,33.52,140.53 349.00,US,,4.016000e+12
3,6,MSFT,Microsoft Corporation,,393.74,-20.45,-4.94%,55.083M,28.583M,2.926T,25.73,344.79 555.45,US,,2.926000e+12
4,7,AMZN,"Amazon.com, Inc.",,222.90,-10.09,-4.33%,68.885M,40.68M,2.383T,33.72,161.38 258.60,US,,2.383000e+12
5,8,TSM,Taiwan Semiconductor Manufacturing Company Lim...,,330.73,4.99,+1.53%,13.769M,12.674M,1.715T,27.17,134.25 351.33,US,,1.715000e+12
6,9,META,"Meta Platforms, Inc.",,670.33,1.34,+0.20%,14.172M,17.617M,1.696T,29.45,479.80 796.25,US,,1.696000e+12
7,10,TSLA,"Tesla, Inc.",,397.36,-8.65,-2.13%,65.297M,72.701M,1.491T,390.70,214.25 498.83,US,,1.491000e+12
8,11,AVGO,Broadcom Inc.,,310.51,2.46,+0.80%,37.996M,30.735M,1.472T,67.16,138.10 414.61,US,,1.472000e+12
9,12,BRK-A,Berkshire Hathaway Inc.,,"756,943.00",-947.00,-0.12%,248,785,1.089T,15.78,"685,150.00 812,855.00",US,,1.089000e+12
10,14,JPM,JPMorgan Chase & Co.,,310.16,-7.11,-2.24%,7.155M,10.146M,1.042T,15.73,202.16 337.25,US,,1.042000e+12
11,15,WMT,Walmart Inc.,,126.94,-1.06,-0.83%,30.436M,29.642M,1.012T,38.96,79.81 129.41,US,,1.012000e+12
12,16,LLY,Eli Lilly and Company,,"1,020.84",-86.28,-7.79%,6.181M,3.373M,915.139B,43.72,"623.78 1,133.95",US,,9.151390e+11
13,18,V,Visa Inc.,,329.13,-0.82,-0.25%,6.693M,7.188M,634.576B,30.90,299.00 375.51,US,,6.345760e+11
14,21,XOM,Exxon Mobil Corporation,,146.08,-1.51,-1.02%,15.277M,17.789M,616.044B,21.45,97.80 147.84,US,,6.160440e+11
15,22,JNJ,Johnson & Johnson,,237.79,3.32,+1.42%,8.362M,9.027M,572.906B,21.13,141.50 235.83,US,,5.729060e+11
16,23,BAC,Bank of America Corporation,,54.94,-0.44,-0.79%,27.362M,37.436M,548.754B,14.29,33.07 57.55,US,,5.487540e+11
17,24,ASML,ASML Holding N.V.,,"1,350.16",11.03,+0.82%,1.672M,1.705M,524.061B,48.17,"578.51 1,493.48",US,,5.240610e+11

In [ ]:
#save as csv
df.to_csv("firm_list.csv", index=False)